# Generated by Django 3.1.7 on 2021-04-04 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210331_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklevel',
            name='stock_unit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
