# Generated by Django 3.1.7 on 2021-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default='CUS-U5EIEVFJ0QWQ', max_length=16)),
                ('type', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], default='B2C', max_length=3)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NA', 'NA')], default='NA', max_length=6)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
