# Generated by Django 3.1.7 on 2021-03-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210329_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CUS-58ZYMQUNAEBY', max_length=16),
        ),
    ]
