# Generated by Django 3.1.7 on 2021-04-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210331_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CUS-HY2QLCXKM5YX', max_length=16),
        ),
    ]
