# Generated by Django 3.1.7 on 2021-04-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210403_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CUS-3LSBYOB8QGAL', max_length=16),
        ),
    ]
