# Generated by Django 3.1.7 on 2021-04-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20210403_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CUS-62M06QJ5XF6A', max_length=16),
        ),
    ]
