# Generated by Django 3.1.7 on 2021-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20210403_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CUS-5U1X0S3FUBJI', max_length=16),
        ),
    ]
