# Generated by Django 3.1.7 on 2021-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20210403_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CUS-EKNKMF4R8R0M', max_length=16),
        ),
    ]
