# Generated by Django 3.1.7 on 2021-04-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20210404_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CUS-6OS2LBMVCXXV', max_length=16),
        ),
    ]
