# Generated by Django 3.1.7 on 2021-04-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_auto_20210404_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CUS-3DQNZR02LD23', max_length=16),
        ),
    ]
