# Generated by Django 3.1.7 on 2021-04-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_auto_20210404_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CUS-JLWEIU6X4AND', max_length=16),
        ),
    ]
