# Generated by Django 3.1.7 on 2021-03-17 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0002_auto_20210317_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B2B', 'B2B'), ('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='ORD-0WIKKUOO67SK', editable=False, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Outstanding', 'Outstanding'), ('Cancel', 'Cancel')], default='Pending', max_length=32)),
                ('create_datetime', models.DateField(auto_now_add=True)),
                ('projected_completed_date', models.DateField(default=datetime.datetime(2021, 3, 24, 14, 42, 29, 98456))),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_quantity', models.PositiveIntegerField(default=0, editable=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktransferorder_requests_created', to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.stocktransferorder')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stocklevel')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='ORD-0WIKKUOO67SK', editable=False, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Outstanding', 'Outstanding'), ('Cancel', 'Cancel')], default='Pending', max_length=32)),
                ('create_datetime', models.DateField(auto_now_add=True)),
                ('projected_completed_date', models.DateField(default=datetime.datetime(2021, 3, 24, 14, 42, 29, 98456))),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_quantity', models.PositiveIntegerField(default=0, editable=False)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extra_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.saleschannel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_orders', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stocklevel')),
            ],
        ),
    ]
