# Generated by Django 3.1.7 on 2021-04-03 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210403_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='channel',
            field=models.ForeignKey(default=orders.models.SalesOrder.default_channel, on_delete=django.db.models.deletion.CASCADE, to='orders.saleschannel'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_id',
            field=models.CharField(default='ORD-5Q20OFOYA0BL', editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='projected_completed_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 10, 15, 44, 32, 893087)),
        ),
        migrations.AlterField(
            model_name='stocktransferorder',
            name='order_id',
            field=models.CharField(default='ORD-5Q20OFOYA0BL', editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktransferorder',
            name='projected_completed_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 10, 15, 44, 32, 893087)),
        ),
    ]
