# Generated by Django 3.1.7 on 2021-04-06 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210404_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_id',
            field=models.CharField(default='ORD-82W7X2BWGEF6', editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='projected_completed_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 13, 10, 57, 5, 160068)),
        ),
        migrations.AlterField(
            model_name='stocktransferorder',
            name='order_id',
            field=models.CharField(default='ORD-82W7X2BWGEF6', editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktransferorder',
            name='projected_completed_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 13, 10, 57, 5, 160068)),
        ),
    ]
